# Generated by Django 2.1 on 2020-09-24 11:04

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='post category')),
                ('cat_des', models.TextField(blank=True, verbose_name='Category Description')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(verbose_name="Users' Comment")),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompleteUser_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('ml', 'male'), ('fl', 'female')], default='ml', max_length=2, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='blog_images', verbose_name='Profile Picture')),
                ('dob', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Post Title')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='picture')),
                ('content', models.TextField(verbose_name='Post')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ManyToManyField(to='blog.Category', verbose_name='Select Post Category')),
                ('poster', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Post By')),
            ],
        ),
        migrations.AddField(
            model_name='comment_user',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
