# Generated by Django 2.1 on 2020-09-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeuser_profile',
            name='approval',
            field=models.BooleanField(default=False, verbose_name='Approve Post'),
        ),
    ]
