# Generated by Django 2.1 on 2020-09-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_completeuser_profile_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeuser_profile',
            name='approval',
        ),
        migrations.AddField(
            model_name='post',
            name='approval',
            field=models.BooleanField(default=False, verbose_name='Approve Post'),
        ),
    ]
