# Generated by Django 2.1 on 2020-02-20 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20200220_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postt',
            new_name='Post',
        ),
    ]
