# Generated by Django 2.1 on 2020-02-20 10:06

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200220_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='picture'),
        ),
        migrations.AddField(
            model_name='post',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='picture'),
        ),
        migrations.AddField(
            model_name='post',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Post By'),
        ),
    ]
