# Generated by Django 2.1 on 2020-10-13 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_user',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Comment_Likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
