# Generated by Django 2.1 on 2020-02-20 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20200220_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('ml', 'male'), ('fl', 'female')], default='ml', max_length=2, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='blog_images', verbose_name='Profile Picture')),
                ('dob', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
