# Generated by Django 2.1 on 2020-03-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_completeprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img4',
        ),
    ]
