# Generated by Django 2.1 on 2020-10-14 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_by',
        ),
        migrations.AddField(
            model_name='comment_user',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.Comment_user'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
