# Generated by Django 2.1 on 2019-12-22 07:22

from django.db import migrations
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_website_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon',
            field=fontawesome.fields.IconField(blank=True, max_length=60),
        ),
    ]
