# Generated by Django 2.1 on 2019-12-22 12:25

from django.db import migrations, models
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_website_app', '0002_services_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img_uploads', verbose_name='post image'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=fontawesome.fields.IconField(blank=True, max_length=60, verbose_name='Font Awesome'),
        ),
    ]
