# Generated by Django 2.1 on 2019-12-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website_app', '0004_auto_20191229_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='site',
            field=models.URLField(null=True, verbose_name='Site Address'),
        ),
    ]
