# Generated by Django 2.1 on 2020-01-03 16:23

from django.db import migrations, models
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_website_app', '0005_portfolio_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abt_img', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='About Image')),
                ('abt_content', models.TextField(verbose_name='About Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan', models.CharField(max_length=100, verbose_name='Your Programming Languages/Tools')),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60, verbose_name='Font Awesome'),
        ),
    ]
