# Generated by Django 2.1 on 2020-01-07 11:01

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_website_app', '0006_auto_20200103_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='l_icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60, verbose_name='Icon Field'),
        ),
    ]
