# Generated by Django 2.1 on 2020-01-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website_app', '0007_languages_l_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='abt_detail',
            field=models.TextField(null=True, verbose_name='About Detail'),
        ),
        migrations.AddField(
            model_name='services',
            name='detail',
            field=models.TextField(null=True, verbose_name='Service Detail'),
        ),
        migrations.AlterField(
            model_name='about',
            name='abt_content',
            field=models.TextField(verbose_name='About Summary'),
        ),
    ]
